name: Build & Deploy
on:
  push:
    branches: [master]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASS}}
      - name: Run NPM
        run: npm run d-push
      - name: Deploy to DO
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{secrets.SSH_PASS}}

          script: |
            cd irc-server
            docker rm -f irc-server
            docker pull mitchelwijt/irc-server
            docker run -dp 3000:3000 --name irc-server mitchelwijt/irc-server
            echo 'Deployment Successful'
          
          
